### ISSUE TITLE
Kiyword-optimizer app in PHP

### ISSUE THREAD

**Issue by janakprajapati** [googleads/keyword-optimizer#1]
Hi, I see that, this is available only in Java. We are using PHP library for the Adwords API and expecting PHP version of this. Are you planing to release this in PHP? Thanks

**Comment by timoboz** [comment]
Hi,

Unfortunately, we are not planning to release this in PHP. If you want to implement similar functionality yourself in PHP, please have a look at our [TargetingIdeaService](https://developers.google.com/adwords/api/docs/guides/targeting-idea-service) / [TrafficEstimatorService](https://developers.google.com/adwords/api/docs/guides/traffic-estimator-service) guides and combine them in a similar fashion.

Cheers,
Timo, AdWords API Team
