### ISSUE TITLE
Problems with building keyword-optimizer-core module

### ISSUE THREAD

**Issue by daannijkamp** [googleads/keyword-optimizer#8]
I'm not sure if I've done something wrong, but I had some problems with building the project. 
In order to build the keyword-optimizer-core module, I had to make some adjustments to the POM file.

https://www.diffchecker.com/q4jsDuS2

(I had some problems with importing [hamcrest core](https://github.com/googleads/keyword-optimizer/blob/master/keyword-optimizer-core/src/test/java/com/google/api/ads/adwords/keywordoptimizer/CommandLineTest.java#L17))

**Comment by dakkad** [comment]
Thanks for your issue daannijkamp I will look into this ASAP.

**Comment by Trevor-Miller** [comment]
I experienced the same issue, and using @daannijkamp's pom.xml allowed me to compile. I was also having issues with hamcrest core.
